create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,avatar_url text,bio text,role text not null default 'buyer' check(role in ('buyer','artist','moderator','admin')),country text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.artworks(id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.profiles(id) on delete cascade,title text not null,artist_name text not null,description text,category text not null,price numeric(14,2) not null check(price>=0),currency text not null default 'USD',cover_image_url text not null,status text not null default 'pending' check(status in ('draft','pending','published','sold','rejected')),featured boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.artwork_images(id uuid primary key default gen_random_uuid(),artwork_id uuid not null references public.artworks(id) on delete cascade,image_url text not null,sort_order integer not null default 0);
create table if not exists public.favorites(user_id uuid references public.profiles(id) on delete cascade,artwork_id uuid references public.artworks(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,artwork_id));
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),buyer_id uuid references public.profiles(id) on delete set null,email text not null,currency text not null,subtotal numeric(14,2) not null default 0,shipping numeric(14,2) not null default 0,total numeric(14,2) not null default 0,payment_status text not null default 'pending' check(payment_status in ('pending','paid','failed','refunded')),fulfillment_status text not null default 'unfulfilled',paystack_reference text unique,shipping_name text,shipping_phone text,shipping_country text,shipping_address text,created_at timestamptz not null default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,artwork_id uuid references public.artworks(id) on delete set null,seller_id uuid references public.profiles(id) on delete set null,title_snapshot text not null,price numeric(14,2) not null,currency text not null,quantity integer not null default 1 check(quantity>0));
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),order_id uuid references public.orders(id) on delete cascade,provider text not null default 'paystack',reference text unique not null,amount numeric(14,2) not null,currency text not null,status text not null default 'pending',raw_event jsonb,created_at timestamptz not null default now());
create index if not exists artworks_status_idx on public.artworks(status);
create index if not exists artworks_seller_idx on public.artworks(seller_id);
create index if not exists artworks_created_idx on public.artworks(created_at desc);
alter table public.profiles enable row level security;
alter table public.artworks enable row level security;
alter table public.artwork_images enable row level security;
alter table public.favorites enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
create policy "published artworks are public" on public.artworks for select to anon,authenticated using(status='published');
create policy "artists manage own artworks" on public.artworks for all to authenticated using(seller_id=(select auth.uid())) with check(seller_id=(select auth.uid()));
create policy "users read own profile" on public.profiles for select to authenticated using(id=(select auth.uid()));
create policy "users update own profile" on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy "users insert own profile" on public.profiles for insert to authenticated with check(id=(select auth.uid()));
create policy "users manage own favorites" on public.favorites for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "buyers read own orders" on public.orders for select to authenticated using(buyer_id=(select auth.uid()));
create policy "buyers read own order items" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.buyer_id=(select auth.uid())));
create or replace function public.handle_new_user() returns trigger language plpgsql security invoker as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')) on conflict(id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();